version: '3.8'  
services:  

  postgres:  
    container_name: postgres  
    image: postgres  
    environment:  
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: 123456  
      POSTGRES_DB: api_db  
    ports:  
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data    

  # pgadmin4:  
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4  
  #   environment:  
  #     PGADMIN_DEFAULT_EMAIL: root@admin.com 
  #     PGADMIN_DEFAULT_PASSWORD: root  
  #   ports:  
  #     - 5050:80
  #   depends_on:
  #     - postgres